### ISSUE TITLE
Provide the schematics as a pdf file too

### ISSUE THREAD

**Issue by Nolaan** [PiStuffing/Quadcopter#1]
Hi,
It would be great if the schematics were available in pdf format. Thanks

**Comment by PiStuffing** [comment]
I don't have schematics, sorry.  The PCB is a simple breadboard which I wired up to meet the code I'd already written.  See here for what the wiring layout was - the nearest to a schematic I have:

http://blog.pistuffing.co.uk/byoaq-bat-i-assembly-electronics/

**Comment by Hollys48** [comment]
Hi, some how the link has sent this email to me, I have nothing to do with
this or any knowledge.
